version: 2
jobs:
  build-test:
    working_directory: '~/sam-zip-city'
    docker:
      - image: cimg/node:18.20.2
        auth:
          username: _json_key
          password: $GCLOUD_CONTAINER_REGISTRY_SERVICE_KEY 
    steps:
      - checkout
      - run: node --version
      - run:
          name: build-and-compile
          command: |
            npm install yarn@1.22.22
            yarn
            yarn tsc-once
      - run:
          name: tests
          command: |
            echo "Running Tests"
            yarn test
      - store_artifacts:
          path: yarn-lock.json
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    working_directory: '~/sam-zip-city'
    docker:
      - image: cimg/node:18.20.2
        auth:
          username: _json_key
          password: $GCLOUD_CONTAINER_REGISTRY_SERVICE_KEY 
    steps:
      - checkout
      - run: node --version
      - attach_workspace:
          at: .
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/sam-zip-city/.npmrc
      - run:
          name: NPM-Deploy
          command: |
            cd ~/sam-zip-city
            echo "Add Version Number"
            npm version ${CIRCLE_TAG} -f -no-git --no-git-tag-version

            echo "Update NPM"
            npm publish --access public .
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-test:
          filters:
            branches:
              only:
                - /.*/
            tags:
              only:
                - /^[0-9]+(\.[0-9]+)*$/
      - deploy:
          requires:
            - build-test
          filters:
            tags:
              only:
                - /^[0-9]+(\.[0-9]+)*$/
            branches:
              ignore:
                - /.*/